name: Deploy Azure Function

on:
  push:
    paths:
      - 'function/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Function'
        uses: azure/functions-action@v1
        with:
          app-name: 'udoni-bot-func'          # Cambia por el nombre real de tu Function App
          package: './function'               # Carpeta donde está tu código
